FROM alpine:3.4
MAINTAINER Tim Lucas <tim@buildkite.com>

ARG BUILDKITE_AGENT_VERSION=stable
ARG DOCKER_VERSION
ARG DOCKER_COMPOSE_VERSION

# See https://pkgs.alpinelinux.org/packages?name=docker
ARG ALPINE_DOCKER_REVISION=r1

LABEL com.buildkite.distro="alpine" \
    com.buildkite.version=${BUILDKITE_AGENT_VERSION} \
    com.buildkite.docker_version=${DOCKER_VERSION} \
    com.buildkite.docker_compose_version=${DOCKER_COMPOSE_VERSION}

# Install tini and remove its backwards compatibility wrapper
RUN apk --no-cache add tini \
    && rm /usr/bin/tini

RUN apk --no-cache add \
      docker=${DOCKER_VERSION}-${ALPINE_DOCKER_REVISION} \
      curl wget bash git perl openssh-client py-pip py-yaml \
    && pip install -U pip docker-compose==${DOCKER_COMPOSE_VERSION} \
    && rm -rf /tmp/* /root/.cache `find / -regex '.*\.py[co]'`

ENV BUILDKITE_AGENT_VERSION=${BUILDKITE_AGENT_VERSION} \
    BUILDKITE_BUILD_PATH=/buildkite/builds \
    BUILDKITE_HOOKS_PATH=/buildkite/hooks

COPY ./scripts/docker/entrypoint.sh ./assets/ssh-env-config.sh /usr/local/bin/
COPY ./assets/${BUILDKITE_AGENT_VERSION}-amd64 /buildkite
RUN ln -s /buildkite/buildkite-agent /usr/local/bin/buildkite-agent

ENTRYPOINT ["tini", "-g", "--", "/usr/local/bin/entrypoint.sh", "buildkite-agent"]
CMD ["start"]
