MAINTAINER Tim Lucas <tim@buildkite.com>

ARG DOCKER_VERSION
ARG DOCKER_COMPOSE_VERSION

RUN curl -fL "https://raw.githubusercontent.com/docker/docker/v${DOCKER_VERSION}/hack/dind" -o /usr/local/sbin/dind \
    && chmod +x /usr/local/sbin/dind

RUN curl -fL "https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}" -o /usr/local/bin/docker \
    && chmod +x /usr/local/bin/docker

RUN curl -fL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

ADD scripts/docker/docker-entrypoint.sh /usr/local/sbin/docker-entrypoint.sh

VOLUME /var/lib/docker
EXPOSE 2375

ENTRYPOINT ["/usr/local/bin/ssh-env-config.sh", "/usr/local/sbin/docker-entrypoint.sh", "buildkite-agent"]
CMD ["start"]
