MAINTAINER Tim Lucas <tim@buildkite.com>

ARG DOCKER_VERSION
ARG DOCKER_COMPOSE_VERSION

LABEL com.buildkite.docker_version=${DOCKER_VERSION} \
    com.buildkite.docker_dind=true \
    com.buildkite.docker_compose_version=${DOCKER_COMPOSE_VERSION}

RUN curl -fL "https://raw.githubusercontent.com/docker/docker/v${DOCKER_VERSION}/hack/dind" -o /usr/local/bin/dind \
    && chmod +x /usr/local/bin/dind

RUN curl -fL "https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o /usr/local/bin/docker \
    && chmod +x /usr/local/bin/docker

RUN curl -fL "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" > /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose

VOLUME /var/lib/docker
EXPOSE 2375