FROM buildkite/agent
MAINTAINER Tim Lucas <tim@buildkite.com>
# BK-TAG: beta

RUN DESTINATION=/buildkite BETA=true bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/master/install.sh`"
